<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>
	<ItemGroup>
		<PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
		<PackageVersion Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.24.2-preview.1" />
		<PackageVersion Include="SonarAnalyzer.CSharp" Version="10.34.0.3385" />
	</ItemGroup>
</Project>